site_name: MIGX
docs_dir: core/components/migx/docs
site_dir: _build/site

repo_url: https://github.com/Bruno17/MIGX

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- TV Configuration: 'tvconfig.md'
- MIGX Configurator CMP: 'configcmp.md'
- Tips and Tricks: 'tipsandtricks.md'
- Donate: 'donate.md'

theme: readthedocs

markdown_extensions:
    - footnotes
    - tables

